version: '3'

volumes:
  fg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - fg_data:/var/lib/postgresql/data
  backend:
    image: chistyakovn/foodgram_backend  
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    image: chistyakovn/foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - db
      - backend
  nginx:
    image: chistyakovn/foodgram_nginx
    ports:
      - 8080:80
    volumes:
      - static:/staticfiles/
      - media:/app/media/
    depends_on:
      - backend
      - frontend
